openapi: 3.0.1
info:
  title: fApi
  description: API Definition of fApi
  version: 1.0.0
servers:
- url: http://localhost:8290/fapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
